name: "ci"

on:
  pull_request:
    branches:
      - "main"
  workflow_dispatch:
    
jobs:
  Spec:
    uses: "puppetlabs/cat-github-actions/.github/workflows/module_ci.yml@main"
    with:
      runs_on: "ubuntu-20.04"
    secrets: "inherit"

  Acceptance:
    needs: "Spec"
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout Source
      uses: actions/checkout@v3

    - name: Activate Ruby 2.7
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: "2.7"

    - name: Cache gems
      uses: actions/cache@v3
      with:
        path: vendor/gems
        key: ${{ runner.os }}-pr-${{ hashFiles('**/Gemfile') }}
        restore-keys: |
          ${{ runner.os }}-pr-
          ${{ runner.os }}-

    - name: Bundle Install
      run: |
        gem install bundler
        bundle install

    - name: Spec Prep
      run: |
        echo ::group::Create the fixtures directory
        bundle exec rake spec_prep
        echo ::endgroup::

    - name: Provision And Setup
      run: |
        bundle exec bolt --modulepath spec/fixtures/modules plan run satellite_pe_tools::test_01_provision
        FILE='spec/fixtures/litmus_inventory.yaml'
        echo INVENTORY_PATH=$FILE >> $GITHUB_ENV

    - name: Inventory
      run: |
        cat ./spec/fixtures/litmus_inventory.yaml

    - name: Install PE and Configure
      run: |
        bundle exec bolt --modulepath spec/fixtures/modules -i $INVENTORY_PATH plan run satellite_pe_tools::test_02_server_setup

    # - name: Run provision Tests
    #   run: |
    #     bundle exec bolt --modulepath spec/fixtures/modules -i $INVENTORY_PATH plan run satellite_pe_tools::test_03_test_run

    # - name: Run Integration tests
    #   run: |
    #     env
    #     bundle exec rake satellite_pe_tools:integration

    - name: Remove test environment
      if: always()
      continue-on-error: true
      run: |
        bundle exec rake litmus:tear_down
